### ISSUE TITLE
Failed to sync: duplicate field `tags`

### ISSUE THREAD

**Issue by liblit** [flathub/com.gitlab.newsflash#4] opened 2020-09-26 21:32 UTC
I've installed News Flash 1.0.5 as a Flatpak from Flathub. I am using news feeds from Feedly, authenticated using a Google account. When I click the "⟳" (Refresh Content) button, News Flash shows an error banner, reporting "Failed to sync." This error banner shows three buttons: "Login", "Go Offline", "�", and "×". When I click the "�" button, News Flash shows an "Error Details" dialog with the following table (but with no column headings):

| | |
|-|-|
|0|Feed API Error|
|1|Error during API call|
|2|Json Error (Json Error)|
|3|duplicate field \`tags\` at line 1 column 85383|

**Comment by jangernert** [comment] 2020-09-27 06:23
duplicate of https://gitlab.com/news-flash/feedly_api/-/issues/11

**Closed by jangernert** 2020-09-27 06:23 UTC
